---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: v4.11.2
  valuesContent: |-
    fullnameOverride: ingress-nginx
    controller:
      kind: DaemonSet
      hostNetwork: true
      hostPort:
        enabled: true
      service:
        enabled: false
      publishService:
        enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      config:
        use-forwarded-headers: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  valuesContent: |-
    global:
      domain: ARGOCD_FQDN

    certificate:
      enabled: true

    crds:
      install: true

    configs:
      params:
        server.insecure: true

    server:
      insecure: true
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: true
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/rewrite-target: /
        labels: {}
        ingressClassName: nginx
        hosts:
        - ARGOCD_FQDN
        https: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: kube-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: base
  targetNamespace: istio-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-istiod
  namespace: kube-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: istiod
  targetNamespace: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  targetNamespace: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-logging-crd
  namespace: kube-system
spec:
  repo: https://charts.rancher.io
  chart: rancher-logging-crd
  targetNamespace: cattle-logging-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-logging
  namespace: kube-system
spec:
  repo: https://charts.rancher.io
  chart: rancher-logging
  targetNamespace: cattle-logging-system
  valuesContent: |-
    logging:
      enabled: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-monitoring-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring-crd
  namespace: kube-system
spec:
  repo: https://charts.rancher.io
  chart: rancher-monitoring-crd
  targetNamespace: cattle-monitoring-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher-monitoring
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: cattle-monitoring-system
